### ISSUE TITLE
"error":"Not found: Collection `techdocs` doesn\'t exist!"

### ISSUE THREAD

**Issue by chrishart0** [kylejtobin/rag_bot#4]
### Issue Summary
I cloned the repo down and spun up the application fresh. After a few tries I got the error posted at the bottom:

The issue appears to be: `"error":"Not found: Collection `techdocs` doesn\'t exist!"`

Checking http://localhost:6333/dashboard#/collections I can see that qdrant doesn't have a `techdocs` collection loaded. Issue appears to be that the LLM expects this to be loaded right off the bat. Unless I missed a step in the README, some process should bootstrap the vectordb with this. 

### Suggested Resolution
Some process should run to bootstrap the vectordb with a techdocs collection. I was able to resolve the issue by using the OpenAPI page to call /scrape and then /process-documents

I would suggest a short python script which is added to the readme as a setup step, prompting the user to enter a URL to scrape or offering a default url. Potentially, the UI could be extended to first check for an existing collection with the name `techdocs`  and if it doesn't exist, request the user enter a URL to scrape.

### Detailed logs from error

```
RAG_BOT_FASTAPI | ERROR:    Exception in ASGI application
RAG_BOT_FASTAPI | Traceback (most recent call last):
RAG_BOT_FASTAPI |   File "/app/src/agent/agent_handler.py", line 144, in chat_with_agent
RAG_BOT_FASTAPI |     response = self.agent_executor.run(input=user_input)
RAG_BOT_FASTAPI |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 508, in run
RAG_BOT_FASTAPI |     return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
RAG_BOT_FASTAPI |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 308, in __call__
RAG_BOT_FASTAPI |     raise e
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/langchain/chains/base.py", line 302, in __call__
RAG_BOT_FASTAPI |     self._call(inputs, run_manager=run_manager)
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/langchain/agents/agent.py", line 1141, in _call
RAG_BOT_FASTAPI |     next_step_output = self._take_next_step(
RAG_BOT_FASTAPI |                        ^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/langchain/agents/agent.py", line 991, in _take_next_step
RAG_BOT_FASTAPI |     observation = tool.run(
RAG_BOT_FASTAPI |                   ^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/langchain/tools/base.py", line 364, in run
RAG_BOT_FASTAPI |     raise e
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/langchain/tools/base.py", line 336, in run
RAG_BOT_FASTAPI |     self._run(*tool_args, run_manager=run_manager, **tool_kwargs)
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/langchain/tools/base.py", line 515, in _run
RAG_BOT_FASTAPI |     else self.func(*args, **kwargs)
RAG_BOT_FASTAPI |          ^^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/app/src/tools/setup.py", line 41, in search_techdocs
RAG_BOT_FASTAPI |     results = search.search_documents()
RAG_BOT_FASTAPI |               ^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/app/src/tools/doc_search.py", line 86, in search_documents
RAG_BOT_FASTAPI |     raise e
RAG_BOT_FASTAPI |   File "/app/src/tools/doc_search.py", line 79, in search_documents
RAG_BOT_FASTAPI |     response = query_engine.query(self.query)
RAG_BOT_FASTAPI |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/llama_index/indices/query/base.py", line 23, in query
RAG_BOT_FASTAPI |     response = self._query(str_or_query_bundle)
RAG_BOT_FASTAPI |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/llama_index/query_engine/retriever_query_engine.py", line 172, in _query
RAG_BOT_FASTAPI |     nodes = self.retrieve(query_bundle)
RAG_BOT_FASTAPI |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/llama_index/query_engine/retriever_query_engine.py", line 120, in retrieve
RAG_BOT_FASTAPI |     nodes = self._retriever.retrieve(query_bundle)
RAG_BOT_FASTAPI |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/llama_index/indices/base_retriever.py", line 22, in retrieve
RAG_BOT_FASTAPI |     return self._retrieve(str_or_query_bundle)
RAG_BOT_FASTAPI |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/llama_index/indices/vector_store/retrievers/retriever.py", line 87, in _retrieve
RAG_BOT_FASTAPI |     return self._get_nodes_with_embeddings(query_bundle)
RAG_BOT_FASTAPI |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/llama_index/indices/vector_store/retrievers/retriever.py", line 164, in _get_nodes_with_embeddings
RAG_BOT_FASTAPI |     query_result = self._vector_store.query(query, **self._kwargs)
RAG_BOT_FASTAPI |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/llama_index/vector_stores/qdrant.py", line 224, in query
RAG_BOT_FASTAPI |     response = self._client.search(
RAG_BOT_FASTAPI |                ^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/qdrant_client/qdrant_client.py", line 298, in search
RAG_BOT_FASTAPI |     return self._client.search(
RAG_BOT_FASTAPI |            ^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/qdrant_client/qdrant_remote.py", line 469, in search
RAG_BOT_FASTAPI |     search_result = self.http.points_api.search_points(
RAG_BOT_FASTAPI |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/qdrant_client/http/api/points_api.py", line 1129, in search_points
RAG_BOT_FASTAPI |     return self._build_for_search_points(
RAG_BOT_FASTAPI |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/qdrant_client/http/api/points_api.py", line 502, in _build_for_search_points
RAG_BOT_FASTAPI |     return self.api_client.request(
RAG_BOT_FASTAPI |            ^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/qdrant_client/http/api_client.py", line 74, in request
RAG_BOT_FASTAPI |     return self.send(request, type_)
RAG_BOT_FASTAPI |            ^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/qdrant_client/http/api_client.py", line 97, in send
RAG_BOT_FASTAPI |     raise UnexpectedResponse.for_response(response)
RAG_BOT_FASTAPI | qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 404 (Not Found)
RAG_BOT_FASTAPI | Raw response content:
RAG_BOT_FASTAPI | b'{"status":{"error":"Not found: Collection `techdocs` doesn\'t exist!"},"time":8.225e-6}'
RAG_BOT_FASTAPI | 
RAG_BOT_FASTAPI | During handling of the above exception, another exception occurred:
RAG_BOT_FASTAPI | 
RAG_BOT_FASTAPI | Traceback (most recent call last):
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
RAG_BOT_FASTAPI |     result = await app(  # type: ignore[func-returns-value]
RAG_BOT_FASTAPI |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
RAG_BOT_FASTAPI |     return await self.app(scope, receive, send)
RAG_BOT_FASTAPI |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 292, in __call__
RAG_BOT_FASTAPI |     await super().__call__(scope, receive, send)
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
RAG_BOT_FASTAPI |     await self.middleware_stack(scope, receive, send)
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
RAG_BOT_FASTAPI |     raise exc
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
RAG_BOT_FASTAPI |     await self.app(scope, receive, _send)
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
RAG_BOT_FASTAPI |     raise exc
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
RAG_BOT_FASTAPI |     await self.app(scope, receive, sender)
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
RAG_BOT_FASTAPI |     raise e
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
RAG_BOT_FASTAPI |     await self.app(scope, receive, send)
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
RAG_BOT_FASTAPI |     await route.handle(scope, receive, send)
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
RAG_BOT_FASTAPI |     await self.app(scope, receive, send)
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
RAG_BOT_FASTAPI |     response = await func(request)
RAG_BOT_FASTAPI |                ^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
RAG_BOT_FASTAPI |     raw_response = await run_endpoint_function(
RAG_BOT_FASTAPI |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
RAG_BOT_FASTAPI |     return await run_in_threadpool(dependant.call, **values)
RAG_BOT_FASTAPI |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
RAG_BOT_FASTAPI |     return await anyio.to_thread.run_sync(func, *args)
RAG_BOT_FASTAPI |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
RAG_BOT_FASTAPI |     return await get_asynclib().run_sync_in_worker_thread(
RAG_BOT_FASTAPI |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
RAG_BOT_FASTAPI |     return await future
RAG_BOT_FASTAPI |            ^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
RAG_BOT_FASTAPI |     result = context.run(func, *args)
RAG_BOT_FASTAPI |              ^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/app/src/api/routes.py", line 40, in chat_endpoint
RAG_BOT_FASTAPI |     return handle_chat(data, agent)
RAG_BOT_FASTAPI |            ^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/app/src/api/handlers.py", line 29, in handle_chat
RAG_BOT_FASTAPI |     response = agent.chat_with_agent(data.user_input)
RAG_BOT_FASTAPI |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI |   File "/app/src/agent/agent_handler.py", line 149, in chat_with_agent
RAG_BOT_FASTAPI |     tb_str = traceback.format_exception(etype=type(e), value=e, tb=e.__traceback__)
RAG_BOT_FASTAPI |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RAG_BOT_FASTAPI | TypeError: format_exception() got an unexpected keyword argument 'etype'
```

**Comment by kyle-aurelius** [comment]
You need to run process docs first! It will make the techdocs collection.

1. Use the scraper to scrape a URL's content and store it locally in directory in markdown

2. Run process docs and that will make a techdocs collection if it doesn't exist.

3. Then try chatting with the content you put in there!
